//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CementingSim.Net.SystemUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CementingSim.Net.SystemUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Deflate压缩解压后的文件与原文件不一致 的本地化字符串。
        /// </summary>
        internal static string ERR_COMPRESSED_ORGINAL_NOTCONSISTENT_DEFLATE {
            get {
                return ResourceManager.GetString("ERR_COMPRESSED_ORGINAL_NOTCONSISTENT_DEFLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gzip压缩解压后的文件与原文件不一致 的本地化字符串。
        /// </summary>
        internal static string ERR_COMPRESSED_ORGINAL_NOTCONSISTENT_GZIP {
            get {
                return ResourceManager.GetString("ERR_COMPRESSED_ORGINAL_NOTCONSISTENT_GZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在生成CRC32校验码时发生缓冲区数据空错误 的本地化字符串。
        /// </summary>
        internal static string ERR_GENERATE_CRC32_ARGUMENTNULL {
            get {
                return ResourceManager.GetString("ERR_GENERATE_CRC32_ARGUMENTNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在生成CRC32校验码时发生缓冲区数据越界错误 的本地化字符串。
        /// </summary>
        internal static string ERR_GENERATE_CRC32_ARGUMENTOUTOFRANGE {
            get {
                return ResourceManager.GetString("ERR_GENERATE_CRC32_ARGUMENTOUTOFRANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在生成CRC32校验码时发生读数据错误 的本地化字符串。
        /// </summary>
        internal static string ERR_GENERATE_CRC32_READING {
            get {
                return ResourceManager.GetString("ERR_GENERATE_CRC32_READING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deflate解压压缩后的文件与原文件不一致 的本地化字符串。
        /// </summary>
        internal static string ERR_ORGINAL_COMPRESSED_NOTCONSISTENT_DEFLATE {
            get {
                return ResourceManager.GetString("ERR_ORGINAL_COMPRESSED_NOTCONSISTENT_DEFLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gzip解压压缩后的文件与原文件不一致 的本地化字符串。
        /// </summary>
        internal static string ERR_ORGINAL_COMPRESSED_NOTCONSISTENT_GZIP {
            get {
                return ResourceManager.GetString("ERR_ORGINAL_COMPRESSED_NOTCONSISTENT_GZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用基础连接串进行数据库连接失败 的本地化字符串。
        /// </summary>
        internal static string ERR_PRELIMINARY_CONNECTION_FAIL {
            get {
                return ResourceManager.GetString("ERR_PRELIMINARY_CONNECTION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取基础连接串失败，请检查安装程序 的本地化字符串。
        /// </summary>
        internal static string ERR_READ_PRELIMINARY_CONNECTION_STRING {
            get {
                return ResourceManager.GetString("ERR_READ_PRELIMINARY_CONNECTION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取真正的连接串失败 的本地化字符串。
        /// </summary>
        internal static string ERR_RETRIEVE_REAL_CONNECTION_STRING_FAIL {
            get {
                return ResourceManager.GetString("ERR_RETRIEVE_REAL_CONNECTION_STRING_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的压缩类型 的本地化字符串。
        /// </summary>
        internal static string ERR_UNKNOWN_COMPRESS_TYPE {
            get {
                return ResourceManager.GetString("ERR_UNKNOWN_COMPRESS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的加密算法 的本地化字符串。
        /// </summary>
        internal static string ERR_UNSUPPORTED_ENCRYPT_ALGORITHM {
            get {
                return ResourceManager.GetString("ERR_UNSUPPORTED_ENCRYPT_ALGORITHM", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;A 放弃 的本地化字符串。
        /// </summary>
        internal static string MSG_BTNABORT {
            get {
                return ResourceManager.GetString("MSG_BTNABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;L 全部 的本地化字符串。
        /// </summary>
        internal static string MSG_BTNALL {
            get {
                return ResourceManager.GetString("MSG_BTNALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;C 取消 的本地化字符串。
        /// </summary>
        internal static string MSG_BTNCANCEL {
            get {
                return ResourceManager.GetString("MSG_BTNCANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;I 忽略 的本地化字符串。
        /// </summary>
        internal static string MSG_BTNIGNORE {
            get {
                return ResourceManager.GetString("MSG_BTNIGNORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;N 否 的本地化字符串。
        /// </summary>
        internal static string MSG_BTNNO {
            get {
                return ResourceManager.GetString("MSG_BTNNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;T 全否 的本地化字符串。
        /// </summary>
        internal static string MSG_BTNNOTTOALL {
            get {
                return ResourceManager.GetString("MSG_BTNNOTTOALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;O 确定 的本地化字符串。
        /// </summary>
        internal static string MSG_BTNOK {
            get {
                return ResourceManager.GetString("MSG_BTNOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;R 重试 的本地化字符串。
        /// </summary>
        internal static string MSG_BTNRETRY {
            get {
                return ResourceManager.GetString("MSG_BTNRETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Y 是 的本地化字符串。
        /// </summary>
        internal static string MSG_BTNYES {
            get {
                return ResourceManager.GetString("MSG_BTNYES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;E 全是 的本地化字符串。
        /// </summary>
        internal static string MSG_BTNYESTOALL {
            get {
                return ResourceManager.GetString("MSG_BTNYESTOALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string MSG_DEFAULTDLGTITLE {
            get {
                return ResourceManager.GetString("MSG_DEFAULTDLGTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemUtils 的本地化字符串。
        /// </summary>
        internal static string MSG_LOCAL_LOG_SOURCE {
            get {
                return ResourceManager.GetString("MSG_LOCAL_LOG_SOURCE", resourceCulture);
            }
        }
    }
}
